// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​n​t​e​r​ ​a​ ​q​u​e​r​y​ ​o​r​ ​U​R​L
	 */
	HEADER_QUERY: string
}

export type TranslationFunctions = {
	/**
	 * Enter a query or URL
	 */
	HEADER_QUERY: () => LocalizedString
}

export type Formatters = {}
